name: Run Daily MLB Predictions

on:
  schedule:
    # This runs the script every day at 14:00 UTC (e.g., 9 AM CDT)
    - cron: '0 14 * * *'
  workflow_dispatch: # This adds a button to run it manually on GitHub

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the prediction script
        run: python mlb_model.py

      # NEW: Updated step to safely commit files only if they exist
      - name: Commit prediction files
        run: |
          # This command checks if any report files exist.
          # It will only proceed if files are found.
          if ls report_*.txt 1> /dev/null 2>&1; then
            echo "Prediction files found. Committing to repository."
            git config --global user.name 'github-actions[bot]'
            git config --global user.email 'github-actions[bot]@users.noreply.github.com'
            git pull
            git add report_*.txt predictions_*.csv
            git commit -m "📊 Add daily predictions for $(date +'%Y-%m-%d')"
            git push
          else
            echo "No prediction files generated. Nothing to commit."
          fi
